apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'ece-userapi-job'
        static_configs:
          - targets: ['ece-userapi-service:3000']
