version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./conf:/usr/src/app/conf
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes --requirepass ""

volumes:
  redis-data: