Vagrant.configure("2") do |config|
  config.vm.box = "sloopstash/ubuntu-22-04"
  config.vm.box_version = "2.1.1"
  config.vm.define "sloopstash-ubuntu-22-04-server"
  config.vm.hostname = "sloopstash-ubuntu-22-04-server"
  config.vm.box_check_update = false
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  config.vm.provider "vmware_fusion" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "1"
    vb.vmx["ethernet0.pcislotnumber"] = "160"
    vb.vmx["ethernet1.pcislotnumber"] = "224"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./Playbooks/provision.yml"  
  end
end